#Acá es para pruebas locales, cambiar por la url de aws cuando esté despleagdo

spring.application.name=trafficgenerator
server.port=8080

# Bookstore API Gateway (Docker, puerto 80)
traffic.target.base-url=http://localhost
# "/" no existe en el gateway → 404. Pon una ruta real de tu API, ej: /api/books
traffic.target.path=/api/books
