events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /health {
            return 200 'ok';
            add_header Content-Type text/plain;
        }

        location /api/books {
            proxy_pass http://catalog_service:5001/api/books;
        }

        location /api/users {
            proxy_pass http://user_service:5002/api/users;
        }

        location /api/cart {
            proxy_pass http://cart_service:5003/api/cart;
        }

        location /api/orders {
            proxy_pass http://order_service:5004/api/orders;
        }

        location /api/reviews {
            proxy_pass http://review_service:5005/api/reviews;
        }

        location /api/wishlists {
            proxy_pass http://wishlist_service:5006/api/wishlists;
        }
    }
}
