events {
    worker_connections 1024;
}
http {
    server {
        listen 80;

        location /health {
            return 200 'ok';
            add_header Content-Type text/plain;
        }

        location /api/books {
            proxy_pass http://internal-bookstore-alb-int-73fdd31-253833027.us-east-1.elb.amazonaws.com/api/books;
        }
        location /api/users {
            proxy_pass http://internal-bookstore-alb-int-73fdd31-253833027.us-east-1.elb.amazonaws.com/api/users;
        }
        location /api/cart {
            proxy_pass http://internal-bookstore-alb-int-73fdd31-253833027.us-east-1.elb.amazonaws.com/api/cart;
        }
        location /api/orders {
            proxy_pass http://internal-bookstore-alb-int-73fdd31-253833027.us-east-1.elb.amazonaws.com/api/orders;
        }
        location /api/reviews {
            proxy_pass http://internal-bookstore-alb-int-73fdd31-253833027.us-east-1.elb.amazonaws.com/api/reviews;
        }
        location /api/wishlists {
            proxy_pass http://internal-bookstore-alb-int-73fdd31-253833027.us-east-1.elb.amazonaws.com/api/wishlists;
        }
    }
}
