apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
  namespace: mybookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      containers:
        - name: wishlist-service
          image: mybookstore/wishlist-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5006
          env:
            - name: PORT
              value: "5006"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"

          readinessProbe:
            httpGet:
              path: /health
              port: 5006
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5006
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: mybookstore
spec:
  selector:
    app: wishlist-service
  ports:
    - port: 5006
      targetPort: 5006