apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: frontend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rontxz/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NGINX_PORT
          value: "80"
        - name: PROXY_PASS
          value: "http://api-gateway-service:80"
