apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 5004
      targetPort: 5004
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: rontxz/order:latest
        ports:
        - containerPort: 5004
        env:
        - name: PORT
          value: "5004"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          value: "postgres"
        - name: DB_HOST
          value: "postgres-order" # Cambiar por el endpoint real de AWS RDS
        - name: DB_PORT
          value: "5432"
