apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: review-service
spec:
  type: ClusterIP # no accesible desde internet
  selector:
    app: review-service
  ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
--- # aqui el deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: review-deployment
spec:
  selector:
    matchLabels:
      app: review-service
  replicas: 1
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: rontxz/review:latest
        ports:
        - containerPort: 5005
        env:
        - name: PORT
          value: "5005"
